[package]
name = "school-project"
version = "0.1.0"
authors = ["alexanderved <avedehin692@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "*"
ash = "0.31.0"
ash-window = "0.5.0"
